apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-configmap
  namespace: microservice
data:
  NODE_ENV: "production"
  PORT: "3003"
  USER_API_URL: 'http://user-service.microservice.svc.cluster.local:3000'
  PRODUCT_API_URL: 'http://product-service.microservice.svc.cluster.local:3001'
  ORDER_API_URL: 'http://order-service.microservice.svc.cluster.local:3002'