apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservice
  labels:
    app: gateway-service
    tier: gateway-service
    environment: production
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP