apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservice
  labels:
    app: product-service
    tier: product-service
    environment: production
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP